name: 🔧 Chore / Task
description: Maintenance, dependencies, CI, or other non-feature work
labels: ["chore"]
body:
  - type: markdown
    attributes:
      value: "## Chore / Task"
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of the project does this affect?
      multiple: true
      options:
        - Web (apps/web)
        - Mobile (apps/mobile)
        - Functions (packages/functions)
        - Shared (packages/shared)
        - Infrastructure (infrastructure/)
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, related issues, or other notes
