import type { Polish } from "polish-inventory-shared";

export const MOCK_POLISHES: Polish[] = [
  {
    id: "1",
    userId: "user-1",
    brand: "OPI",
    name: "Big Apple Red",
    color: "Red",
    colorHex: "#C4113C",
    finish: "cream",
    collection: "Classics",
    quantity: 1,
    size: "15ml",
    rating: 5,
    notes: "Perfect classic red, great formula",
    tags: ["favorite", "classic"],
    createdAt: "2025-12-01T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "2",
    userId: "user-1",
    brand: "Essie",
    name: "Ballet Slippers",
    color: "Pink",
    colorHex: "#F4C2C2",
    finish: "sheer",
    collection: "Essie Originals",
    quantity: 2,
    size: "13.5ml",
    rating: 4,
    tags: ["everyday", "classic"],
    createdAt: "2025-12-05T00:00:00Z",
    updatedAt: "2025-12-05T00:00:00Z",
  },
  {
    id: "3",
    userId: "user-1",
    brand: "ILNP",
    name: "Mega",
    color: "Teal",
    colorHex: "#008080",
    finish: "holographic",
    quantity: 1,
    size: "12ml",
    rating: 5,
    notes: "Insane holo sparkle",
    tags: ["indie", "favorite"],
    createdAt: "2025-12-10T00:00:00Z",
    updatedAt: "2025-12-10T00:00:00Z",
  },
  {
    id: "4",
    userId: "user-1",
    brand: "Zoya",
    name: "Willa",
    color: "Mauve",
    colorHex: "#C9A0DC",
    finish: "cream",
    collection: "Naturel",
    quantity: 1,
    size: "15ml",
    rating: 4,
    tags: ["everyday", "work"],
    createdAt: "2025-12-15T00:00:00Z",
    updatedAt: "2025-12-15T00:00:00Z",
  },
  {
    id: "5",
    userId: "user-1",
    brand: "OPI",
    name: "Lincoln Park After Dark",
    color: "Dark Purple",
    colorHex: "#3B1F2B",
    finish: "cream",
    collection: "Classics",
    quantity: 1,
    size: "15ml",
    rating: 5,
    tags: ["favorite", "fall"],
    createdAt: "2025-12-20T00:00:00Z",
    updatedAt: "2025-12-20T00:00:00Z",
  },
  {
    id: "6",
    userId: "user-1",
    brand: "Cirque Colors",
    name: "Lullaby",
    color: "Lavender",
    colorHex: "#B4A7D6",
    finish: "cream",
    collection: "Aura",
    quantity: 1,
    size: "12.5ml",
    rating: 4,
    tags: ["indie", "spring"],
    createdAt: "2026-01-02T00:00:00Z",
    updatedAt: "2026-01-02T00:00:00Z",
  },
  {
    id: "7",
    userId: "user-1",
    brand: "Holo Taco",
    name: "Scattered Holo Taco",
    color: "Clear/Silver",
    colorHex: "#C0C0C0",
    finish: "topper",
    quantity: 1,
    size: "13ml",
    rating: 5,
    notes: "Goes over everything",
    tags: ["topper", "favorite"],
    createdAt: "2026-01-05T00:00:00Z",
    updatedAt: "2026-01-05T00:00:00Z",
  },
  {
    id: "8",
    userId: "user-1",
    brand: "Essie",
    name: "Wicked",
    color: "Dark Red",
    colorHex: "#4A0000",
    finish: "cream",
    collection: "Essie Originals",
    quantity: 1,
    size: "13.5ml",
    rating: 3,
    notes: "Streaky first coat, needs 3 coats",
    tags: ["fall", "vampy"],
    createdAt: "2026-01-10T00:00:00Z",
    updatedAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "9",
    userId: "user-1",
    brand: "ILNP",
    name: "Cygnus Loop",
    color: "Multichrome",
    colorHex: "#4B0082",
    finish: "multichrome",
    quantity: 1,
    size: "12ml",
    rating: 5,
    notes: "Shifts from purple to copper to green",
    tags: ["indie", "favorite", "special"],
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    id: "10",
    userId: "user-1",
    brand: "OPI",
    name: "Funny Bunny",
    color: "White",
    colorHex: "#F5F0EB",
    finish: "sheer",
    collection: "Soft Shades",
    quantity: 1,
    size: "15ml",
    rating: 4,
    tags: ["everyday", "classic"],
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-01-20T00:00:00Z",
  },
];

export function getPolishById(id: string): Polish | undefined {
  return MOCK_POLISHES.find((p) => p.id === id);
}

export const BRANDS = [...new Set(MOCK_POLISHES.map((p) => p.brand))].sort();

export const FINISHES = [
  "cream",
  "shimmer",
  "glitter",
  "metallic",
  "matte",
  "jelly",
  "holographic",
  "duochrome",
  "multichrome",
  "flake",
  "topper",
  "sheer",
  "other",
] as const;
